version: "3.8"
services:   
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - 3306:3306
    networks:
      - webapp-net  
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: sanchit
      MYSQL_PASSWORD: 1234567890
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
      
  app:
    depends_on:
      - mysqldb
    build: .
    ports:
      - 8080:8081
    environment: 
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/webapp
      - spring.datasource.username=sanchit
      - spring.datasource.password=1234567890
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      - webapp-net  
    stdin_open: true
    tty: true
    restart: on-failure

networks:
  webapp-net:

volumes:
  db: